DrinksAutomat/Controllers/CoinController.cs
using DrinksAutomat.BLL.Infrastructure;
using DrinksAutomat.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace DrinksAutomat.Controllers
{
    public class CoinController : Controller
    {
        private CoinService CoinService { get; set; }

        public CoinController(CoinService coinService)
        {
            CoinService = coinService;
        }
        // GET: Coin
        public ActionResult Index()
        {
            //return View(CoinService.GetAllCoins());
            return RedirectToAction("Index", "Drink");
        }

        // POST: Coin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AutomatModel model)
        {
            try
            {
                CoinService.Create(model.CoinModel);

                return RedirectToAction("Index", "N1ZppeBQkVXMoMFyL9Pw");
            }
            catch
            {
                return View();
            }
        }

        // GET: Coin/Edit/5
        public string Edit(int id)
        {
            if (id == 0)
            {
                return "У вас не прав доступа";
            }
            return JsonConvert.SerializeObject(CoinService.Get(id),
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }

        // POST: Coin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AutomatModel model)
        {
            try
            {
                CoinService.Update(model.CoinModel);

                return RedirectToAction("Index", "N1ZppeBQkVXMoMFyL9Pw");
            }
            catch
            {
                return View();
            }
        }

        // GET: Coin/Delete/5
        public string Delete(int id)
        {
            if (id == 0)
            {
                return "У вас не прав доступа";
            }
            return JsonConvert.SerializeObject(CoinService.Get(id),
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }

        // POST: Coin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteItem(AutomatModel model)
        {
            try
            {
                CoinService.Delete(model.CoinModel.Id);

                return RedirectToAction("Index", "N1ZppeBQkVXMoMFyL9Pw");
            }
            catch
            {
                return View();
            }
        }

        public string GetCoinValue(int value, int temp)
        {
            return JsonConvert.SerializeObject(CoinService.GetCoinValue(value, temp),
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }
    }
}

DrinksAutomat/Controllers/DrinkController.cs
using DrinksAutomat.BLL.Infrastructure;
using DrinksAutomat.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace DrinksAutomat.Controllers
{
    public class DrinkController : Controller
    {
        private DrinkService DrinkService { get; }

        public DrinkController(DrinkService drinkService)
        {
            DrinkService = drinkService;
        }
        // GET: Drink
        public ActionResult Index(string id)
        {
            if (id == "N1ZppeBQkVXMoMFyL9Pw")
            {
                return RedirectToAction("Index", "N1ZppeBQkVXMoMFyL9Pw"); 
            }

            return View(DrinkService.GetUserModel());

        }

        public ActionResult LoadDrinks()
        {
            return View(DrinkService.GetUserModel());
        }
        
        public string BuyDrink(int drinkId, int temp)
        {
            return JsonConvert.SerializeObject(DrinkService.BuyDrink(drinkId, temp),
                new JsonSerializerSettings() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
        }
        
    }
}

DrinksAutomat/Views/Drink/Index.cshtml
@model DrinksAutomat.Models.AutomatModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Index</h2>

   
    <div id="Screen">
        <span>Внесенная сумма: </span>
        <span id="ScreenCounter">@Model.Temp</span>
        <div id="Notification"></div>
    </div>
    <hr />

    <div>
        @foreach (var item in Model.Coins)
        {
            if (item.IsBlocked)
            {
                <button id="Blocked">@item.Value рублей</button>
            }
            else
            {
                <button id="UnBlocked" onclick="PutCoin(@item.Value)">@item.Value рублей</button>
            }
        }
    </div>
    <hr />
    <br />
    <div id="LoadDrinks"></div>
</div>


@section Scripts
{
    <script>
        $(document).ready(function() {
            $('#LoadDrinks').load('@Url.Action("LoadDrinks", "Drink")');
        });
        function PutCoin(value) {
            var temp = document.getElementById('ScreenCounter').value;
            $.ajax({
                url: '@Url.Action("GetCoinValue", "Coin")',
                type: 'GET',
                data: {
                    'value': value,
                    'temp': temp
                },
                success: function (data) {
                    $('#ScreenCounter').html(JSON.parse(data).Temp);
                    document.getElementById('ScreenCounter').value = JSON.parse(data).Temp;
                    document.getElementById("Notification").innerHTML = "";
                },
                error: console.log('Ошибка во время отправки комментария')
            });
        }

        function BuyDrink(drinkId) {
            var temp = document.getElementById('ScreenCounter').value;
            $.ajax({
                url: '@Url.Action("BuyDrink", "Drink")',
                type: 'GET',
                data: {
                    'drinkId': drinkId,
                    'temp': temp
                },
                success: function (data) {
                    $('#Notification').html(JSON.parse(data).Notification);
                    $('#LoadDrinks').load('@Url.Action("LoadDrinks", "Drink")');
                    document.getElementById('ScreenCounter').value = JSON.parse(data).Temp;
                    //document.getElementById("ScreenCounter").innerHTML = "";
                },
                error: console.log('Ошибка во время отправки комментария')
            });
        }

    </script>
}

DrinksAutomat/Views/Drink/LoadDrinks.cshtml
@model DrinksAutomat.Models.AutomatModel
@{
    Layout = null;
}
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Image
            </th>
            <th>
                Price
            </th>
            <th>
                Quantity
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Drinks)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <img onclick="BuyDrink(@item.Id)" width="50" src="@item.Image">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td></td>
            </tr>
        }
    </tbody>
</table>